version: "3.9"

services:

  redis:
    image: redis:7.2
    container_name: tf_idf_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    env_file:
      - ../.env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - services

  app:
    build:
      context: ../
      dockerfile: ./src/app/Dockerfile
    env_file:
      - ../.env
    container_name: tf_idf_app
    restart: always
    networks:
      - services
    ports:
      - 80:80

volumes:
  redis_data:

networks:
  services:
    name: tf_idf_service
